apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: mini-app
spec:
  build:
    useBuildKit: true
  environments:
    - name: dev
      build:
        from: main
    - name: dev2
      build:
        from: main
        webhookEnabled: true
    - name: dev3
      build:
        from: main
        webhookEnabled: false
  components:
    - name: app1
      src: ./app1
      ports:
        - name: http
          port: 8080
      variables:
        VAR1: v8
    - name: app3
      src: ./app2
      ports:
        - name: http
          port: 8080
      variables:
        VAR1: v8
