apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: mini-app
spec:
  build:
    useBuildKit: true
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: server
      image: nginxinc/nginx-unprivileged
      variables:
        VAR1: v5
