apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: mini-app
spec:
  build:
    useBuildKit: true
  environments:
    - name: dev
      build:
        from: (main|v1.*)
    - name: dev2
      build:
        from: (main|v1.*)
        fromType: branch
    - name: dev3
      build:
        from: (main|v1.*)
        fromType: tag
    - name: dev4
      build:
        from: (main|v1.*)
        webhookEnabled: false
  components:
    - name: server
      src: ./app1
      ports:
        - name: http
          port: 8080
      variables:
        VAR1: v27
