apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: mini-app
spec:
  build:
    useBuildKit: true
    useBuildCache: true
  environments:
    - name: dev
      build:
        from: main
    - name: dev2
      build:
        from: main
  components:
    - name: app
      src: api/legacy-n2g/
      dockerfileName: api/Dockerfile
      ports:
        - name: http
          port: 8080
    - name: app1
      src: ./app1
      ports:
        - name: http
          port: 8080
    - name: app2
      src: ./app2
      ports:
        - name: http
          port: 8080
