apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: mini-app
spec:
  build:
    useBuildKit: true
    secrets:
      - SECRET_1
      - SECRET_2
  environments:
    - name: dev
      build:
        from: main
    - name: dev2
      build:
        from: main
  components:
    - name: server
      replicas: 0
      ports:
        - name: http
          port: 8080
      variables:
        VAR1: v5
      publicPort: http
    - name: server2
      replicas: 0
      ports:
        - name: http
          port: 8080
      publicPort: http
  dnsAlias:
    - alias: myapp1
      component: server
      environment: dev
    - alias: myapp2
      component: server
      environment: dev2
    - alias: myapp3777
      component: server2
      environment: dev
  dnsExternalAlias:
    - alias: myapp721.equinor.com
      component: server2
      environment: dev
    - alias: myapp422.equinor.com
      component: server
      environment: dev2
  dnsAppAlias:
    environment: dev
    component: server