apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: mini-app
spec:
  build:
    useBuildKit: true
  environments:
    - name: dev
      build:
        from: main
    - name: dev2
      build:
        from: main
    - name: dev3
      build:
        from: main
    - name: dev4
      build:
        from: main
  components:
    - name: server
      identity:
        azure:
          clientId: "7ef841f8-a263-45ea-8993-683cc6817ae2"
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
        - environment: dev2
          identity:
            azure:
              clientId: "abc"
        - environment: dev3
          identity:
            azure: {}
        - environment: dev4
          identity: {}
