apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: mini-app
spec:
  build:
    useBuildKit: true
  environments:
    - name: devd
      build:
        from: main
    - name: auth2-no-redis
      build:
        from: main
    - name: auth2-ext-redis
      build:
        from: main
    - name: auth2-sys-redis
      build:
        from: main
  components:
    - name: server2
      src: ./app2
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
        - environment: auth2-sys-redis
          authentication:
            oauth2:
              clientId: "5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6"
              credentials: azureWorkloadIdentity
              sessionStoreType: systemManaged
        - environment: auth2-ext-redis
          authentication:
            oauth2:
              clientId: "5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6"
              credentials: azureWorkloadIdentity
              sessionStoreType: redis
              redisStore:
                connectionUrl: redis://auth-state:6379
        - environment: auth2-no-redis
          authentication:
            oauth2:
              clientId: "5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6"
              credentials: azureWorkloadIdentity
    - name: server
      authentication:
        oauth2:
          clientId: "5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6"
          credentials: azureWorkloadIdentity
      src: ./app2
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
        - environment: auth2-sys-redis
          authentication:
            oauth2:
              sessionStoreType: systemManaged
        - environment: auth2-ext-redis
          authentication:
            oauth2:
              sessionStoreType: redis
              redisStore:
                connectionUrl: redis://auth-state:6379
    - name: auth-state
      image: bitnami/redis:8.0
      secrets:
        - REDIS_PASSWORD
      ports:
        - name: redis
          port: 6379
      enabled: false
      environmentConfig:
        - environment: auth2-ext-redis
          enabled: true
