apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: mini-app
spec:
  build:
    useBuildKit: true
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: server
      # identity:
      #   azure:
      #     clientId: "7ef841f8-a263-45ea-8993-683cc6817ae2"
      authentication:
        oauth2:
          clientId: "5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6"
          # credentials: azureWorkloadIdentity
          skipAuthRoutes:
          - GET=^/api/v1/resource/[0-9]+/
          - POST=^/login/
          sessionStoreType: redis
          redisStore:
            connectionUrl: redis://redis:6379      
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
      - environment: dev
    - name: redis
      image: bitnami/redis:latest
      secrets:
        - REDIS_PASSWORD
      ports:
        - name: redis
          port: 6379    
