apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: mini-app
spec:
  build:
    useBuildKit: true
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: app1
      src: api/legacy-n2g/
      dockerfileName: api/Dockerfile
      ports:
        - name: http
          port: 8080
      variables:
        VAR1: v4
